 spring.application.name=bombaBet

spring.datasource.url=jdbc:mysql://localhost:3306/bolao
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Aviso: senha vazia porque uso XAMPP